"""Argument parser shared by backbone training and critique scripts."""
import argparse

def parse_args():
    parse = argparse.ArgumentParser(description="Run Reproduct")
    parse.add_argument('--seed', type=int, default=2025)
    parse.add_argument('--gpu', type=int, default=0)
    parse.add_argument('--cuda', type=bool, default=True)
    parse.add_argument('--log', type=str, default='None')
    parse.add_argument('--dataset_path', type=str, default='./dataset/')
    parse.add_argument('--dataset_type', type=str, default='.txt')
    parse.add_argument('--dataset', type=str, default='movielens-1m')
    parse.add_argument('--top_K', type=str, default='[5, 10, 20]')
    parse.add_argument('--train_epoch', type=int, default=600)
    parse.add_argument('--critique_round_num', type=int, default=5)
    parse.add_argument('--critique_epoch', type=int, default=12)
    parse.add_argument('--early_stop', type=int, default=10)
    parse.add_argument('--early_stop_metric', type=str, default='recall10',
                       choices=['recall5', 'recall10', 'recall20', 'ndcg5', 'ndcg10', 'ndcg20', 'train_ndcg5'])
    parse.add_argument('--embedding_size', type=int, default=64)
    parse.add_argument('--train_batch_size', type=int, default=2048)
    parse.add_argument('--test_batch_size', type=int, default=2048)
    parse.add_argument('--learn_rate', type=float, default=0.002)
    parse.add_argument('--critique_rate', type=float, default=0.002)
    parse.add_argument('--reg_lambda', type=float, default=0.0001)
    parse.add_argument('--gcn_layer', type=int, default=3)
    parse.add_argument('--test_frequency', type=int, default=1)
    parse.add_argument('--sparsity_test', type=int, default=0)
    parse.add_argument('--tau', type=float, default=0.28)
    parse.add_argument('--ssl_lambda', type=float, default=5.0)
    parse.add_argument('--encoder', type=str, default='MF')
    parse.add_argument('--critique_encoder', type=str, default='MF', choices=['MF', 'GCN'])

    parse.add_argument('--num_bpr_neg', type=int, default=10)
    parse.add_argument('--num_cl_neg', type=int, default=1000)
    parse.add_argument('--critique_cl_lambda', type=float, default=1.0)
    parse.add_argument('--critique_pos_lambda', type=float, default=0.8)
    parse.add_argument('--critique_neg_lambda', type=float, default=1.0)
    parse.add_argument('--lambda_cf', type=float, default=0.8)
    parse.add_argument('--lambda_cross', type=float, default=0.0)
    parse.add_argument('--prd_pos_lambda', type=float, default=0.0)
    parse.add_argument('--prd_tau', type=float, default=0.05)
    parse.add_argument('--prd_gap_weight', type=float, default=1.0)
    parse.add_argument('--force_neg_anchor', action='store_true', default=False)

    parse.add_argument('--shuffle_neg_scores', action='store_true', default=False)
    parse.add_argument('--reverse_neg_scores', action='store_true', default=False)
    parse.add_argument('--neg_dropout', type=float, default=0.0)
    parse.add_argument('--score_noise_std', type=float, default=0.0)
    parse.add_argument('--perturb_seed', type=int, default=2025)

    parse.add_argument('--neg_gate_mode', type=str, default='none',
                       choices=['none', 'linear', 'power', 'softmax', 'hard_topk', 'hard_thresh'])
    parse.add_argument('--neg_gate_gamma', type=float, default=5.0)
    parse.add_argument('--neg_gate_topk', type=int, default=5)
    parse.add_argument('--neg_gate_cftable', type=str, default=None)
    parse.add_argument('--neg_gate_invert', action='store_true', default=False)

    parse.add_argument('--npc_residual', action='store_true', default=False)
    parse.add_argument('--npc_full', action='store_true', default=False)
    parse.add_argument('--npc_prop', action='store_true', default=False)
    parse.add_argument('--npc_prop_neg', action='store_true', default=False)
    parse.add_argument('--npc_alpha', type=float, default=1.0)
    parse.add_argument('--npc_alpha_neg', type=float, default=1.0)

    parse.add_argument('--out', type=str, default=None)
    parse.add_argument('--critique_round_path', type=str, default='./experiments/top200/critique_round/')
    parse.add_argument('--backbone', type=str, default=None)
    parse.add_argument('--save_name', type=str, default=None)

    return parse.parse_args()
