"""Argument parser for simulate_rllm (residual-LLM multi-task critique parameters)."""
import argparse

def parse_args():
    parse = argparse.ArgumentParser(description="Run Reproduct")
    parse.add_argument('--seed', type=int, default=2025)
    parse.add_argument('--gpu', type=int, default=0)
    parse.add_argument('--cuda', type=bool, default=True)
    parse.add_argument('--log', type=str, default='None')
    parse.add_argument('--dataset_path', type=str, default='./dataset/')
    parse.add_argument('--dataset_type', type=str, default='.txt')
    parse.add_argument('--dataset', type=str, default='movielens-1m')
    parse.add_argument('--top_K', type=str, default='[5, 10, 20]')
    parse.add_argument('--train_epoch', type=int, default=600)
    parse.add_argument('--critique_round_num', type=int, default=5)
    parse.add_argument('--critique_epoch', type=int, default=12)
    parse.add_argument('--early_stop', type=int, default=10)
    parse.add_argument('--early_stop_metric', type=str, default='recall10',
                       choices=['recall5', 'recall10', 'recall20', 'ndcg5', 'ndcg10', 'ndcg20', 'train_ndcg5'])
    parse.add_argument('--embedding_size', type=int, default=64)
    parse.add_argument('--train_batch_size', type=int, default=2048)
    parse.add_argument('--test_batch_size', type=int, default=2048)
    parse.add_argument('--learn_rate', type=float, default=0.002)
    parse.add_argument('--critique_rate', type=float, default=0.001)
    parse.add_argument('--reg_lambda', type=float, default=0.0001)
    parse.add_argument('--gcn_layer', type=int, default=3)
    parse.add_argument('--test_frequency', type=int, default=1)
    parse.add_argument('--sparsity_test', type=int, default=0)
    parse.add_argument('--tau', type=float, default=0.28)
    parse.add_argument('--ssl_lambda', type=float, default=5.0)
    parse.add_argument('--encoder', type=str, default='MF')
    parse.add_argument('--critique_encoder', type=str, default='MF', choices=['MF', 'GCN'])

    parse.add_argument('--num_bpr_neg', type=int, default=10)
    parse.add_argument('--num_cl_neg', type=int, default=1000)
    parse.add_argument('--critique_cl_lambda', type=float, default=1.0)
    parse.add_argument('--critique_pos_lambda', type=float, default=0.8)
    parse.add_argument('--critique_neg_lambda', type=float, default=1.0)
    parse.add_argument('--lambda_cf', type=float, default=0.8)
    parse.add_argument('--lambda_cross', type=float, default=0.0)
    parse.add_argument('--prd_pos_lambda', type=float, default=0.0)
    parse.add_argument('--prd_tau', type=float, default=0.05)
    parse.add_argument('--prd_gap_weight', type=float, default=1.0)
    parse.add_argument('--force_neg_anchor', action='store_true', default=False)

    parse.add_argument('--neg_gate_mode', type=str, default='none',
                       choices=['none', 'linear', 'power', 'softmax', 'hard_topk', 'hard_thresh'])
    parse.add_argument('--neg_gate_gamma', type=float, default=5.0)
    parse.add_argument('--neg_gate_topk', type=int, default=5)
    parse.add_argument('--neg_gate_cftable', type=str, default=None)
    parse.add_argument('--neg_gate_invert', action='store_true', default=False)

    parse.add_argument('--npc_residual', action='store_true', default=False)
    parse.add_argument('--npc_full', action='store_true', default=False)
    parse.add_argument('--npc_prop', action='store_true', default=False)
    parse.add_argument('--npc_prop_neg', action='store_true', default=False)
    parse.add_argument('--npc_alpha', type=float, default=1.0)
    parse.add_argument('--npc_alpha_neg', type=float, default=1.0)

    parse.add_argument('--rllm_mode', type=str, default='none', choices=['none', 'reg', 'pair'])
    parse.add_argument('--rllm_lambda', type=float, default=1.0)
    parse.add_argument('--rllm_tau', type=float, default=0.05)
    parse.add_argument('--rllm_pred_space', action='store_true', default=False)
    parse.add_argument('--rllm_beta', type=float, default=0.0)
    parse.add_argument('--rllm_within', type=float, default=1.0)
    parse.add_argument('--rllm_pool_size', type=int, default=60)
    parse.add_argument('--rllm_propagate', action='store_true', default=False)
    parse.add_argument('--rllm_polarity', action='store_true', default=False)
    parse.add_argument('--rllm_alpha_neg', type=float, default=0.3)

    parse.add_argument('--delta_reg_lambda', type=float, default=0.0)
    parse.add_argument('--no_cer_random_ref', action='store_true', default=False)
    parse.add_argument('--no_cer_critique_replay', action='store_true', default=False)

    parse.add_argument('--use_cer_margin', action='store_true', default=False)
    parse.add_argument('--cer_margin', type=float, default=0.5)
    parse.add_argument('--cer_tau', type=float, default=0.1)
    parse.add_argument('--cer_gamma', type=float, default=1.0)
    parse.add_argument('--cer_cri_neg_k', type=int, default=20)

    parse.add_argument('--lcri_gate_aware', action='store_true', default=False)
    parse.add_argument('--lcri_gate_M', type=float, default=1.0)

    parse.add_argument('--use_semantic_offset_in_lcri', action='store_true', default=False)
    parse.add_argument('--so_M', type=float, default=1.0)
    parse.add_argument('--cri_temperature', type=float, default=1.0)

    parse.add_argument('--use_ccr', action='store_true', default=False)
    parse.add_argument('--ccr_joint_score', action='store_true', default=False)
    parse.add_argument('--ccr_tau', type=float, default=1.0)
    parse.add_argument('--ccr_M', type=float, default=1.0)
    parse.add_argument('--integ_additive', action='store_true', default=False)

    parse.add_argument('--prot_lambda', type=float, default=0.0)
    parse.add_argument('--cl_hardneg_critique', action='store_true', default=False)

    parse.add_argument('--integ_M', type=float, default=10.0)
    parse.add_argument('--integ_gamma', type=float, default=8.0)
    parse.add_argument('--integ_hard_inference', action='store_true', default=True)
    parse.add_argument('--integ_smooth', type=float, default=0.0)
    parse.add_argument('--integ_no_hard_inf', action='store_true', default=False)
    parse.add_argument('--integ_exclude_cffp', action='store_true', default=False)
    parse.add_argument('--integ_cffp_file', type=str, default=None)
    parse.add_argument('--integ_fp_file', type=str, default=None)
    parse.add_argument('--integ_incremental_gate', action='store_true', default=False)
    parse.add_argument('--integ_gate_schedule', type=str, default='strength', choices=['strength', 'round_path'])

    parse.add_argument('--out', type=str, default=None)
    parse.add_argument('--critique_round_path', type=str, default='./experiments/top200/critique_round/')
    parse.add_argument('--backbone', type=str, default=None)
    parse.add_argument('--save_name', type=str, default=None)

    return parse.parse_args()
